export const FORM_NEW_PROJECT = 'FORM_NEW_PROJECT';
export const GET_PROJECTS_SIDEBAR = 'GET_PROJECTS_SIDEBAR';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';