export const FORM_NEW_PROJECT = 'FORM_NEW_PROJECT';
export const GET_PROJECTS_SIDEBAR = 'GET_PROJECTS_SIDEBAR';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const GET_SELECTED_PROJECT = "GET_SELECTED_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const TASKS_PROJECT = "TASKS_PROJECT";
export const ADD_NEW_TASK = "ADD_NEW_TASK";