export const FORM_NEW_PROJECT = 'FORM_NEW_PROJECT';
export const GET_PROJECTS_SIDEBAR = 'GET_PROJECTS_SIDEBAR';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const GET_SELECTED_PROJECT = "GET_SELECTED_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const TASKS_PROJECT = "TASKS_PROJECT";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const VALIDATE_TASK_FORM = 'VALIDATE_TASK_FORM';
export const DELETE_TASK = 'DELETE_TASK';
export const TASK_STATE = 'TASK_STATE';
export const CURRENT_TASK = 'CURRENT_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAN_TASK ='CLEAN_TASK';

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const SUCCESSFUL_SIGNUP = "SUCCESSFUL_SIGNUP";
export const UNSUCCESSFUL_SIGNUP = "UNSUCCESSFUL_SIGNUP";
export const GET_USER = "GET_USER";
export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN";
export const UNSUCCESSFUL_LOGIN = "UNSUCCESSFUL_LOGIN";
export const LOGOUT = "LOGOUT"
